name: Build a04br3-build Image

on:
  push:
    branches:
      - main
    paths:
      - a04br3-build/Dockerfile

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build image
      run: docker build -t awayume/a04br3-build:latest a04br3-build
    - name: Push image
      env:
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: |
        docker login -u awayume -p $DOCKER_PASSWORD
        docker push awayume/a04br3-build:latest
